biscuit_test.go, builder.go
- Add unit tests for uncovered biscuit methods (mostly error checks)
- Remove unused method from builder.
=> Add biscuit unit tests

biscuit_test.go, proto.go
A nonsense check was making it impossible to deserialize a biscuit
having defined constraint, as a datalog.Constraint name type would
always return "Variable", thus making it impossible to deduct the proper
protobuf constraint kind.
=> Fix constraint conversion

biscuit_test.go, example_test.go, samples/samples_test.go, verifier.go
Those methods doesn't belong to the general verifier interface,
and depends on the biscuit usage context. A custom verifier
have been added in example, showing how to extend the generic
one with similar helpers.
=> remove verifier addResource, addOperation and setTime

proto.go, proto_test.go
this helped fix 5 bugs:
- StringInSet was loosing the constraint name in the datalog -> proto
conversion
- IntNotInSet  was loosing the set values in the proto -> datalog
conversion
- StringNotInSet was loosing the set values in the proto -> datalog
conversion
- BytesInSet was not encoding the []byte in hex in the proto -> datalog
conversion
- BytesNotInSet was not encoding the []byte in hex in the proto ->
datalog conversion
=> add tests for datalog <-> proto conversions

biscuit.go, biscuit_test.go, builder.go, datalog/datalog_test.go, example_test.go, types.go
Fix an issue where the defaultSymbolTable get modified due to shared references used in the biscuit builder and unmarshaller, ending getting biscuits with invalid symbols / blocks with empty symbol table.
=> Fix symbols references

biscuit.go, experiments/pop_test.go, go.sum, verifier.go, verifier_test.go
This allows to search for a block containing a specific fact name, and
retrieve it's index. This is useful in proof of possession flow, where
the verifier needs to hash all the blocks before the one containing the
user signature.
Also fixed the `biscuit.SHA256Sum` function which were not including 
the root key in the hash.
=> Add verifier GetBlockID

go.sum, parser/grammar.go, parser/grammar_test.go, parser/parser.go
This replace the default golang text scanner grammar by a full custom
one for more control over biscuit types and structures (ie: comments support).
The lexer will now rely on `biscuitLexerRules` instead of default golang text scanner.
=> Update parser grammar

parser/GRAMMAR.md, parser/grammar.go, parser/grammar_test.go, parser/parser_test.go
this removes the leading '*' from rules, and ensure empty heads are
allowed.
fix #43
=> update rule syntax

datalog/datalog.go, datalog/datalog_test.go
introduce run limits to the datalog world,
allowing to stop the execution when the processing
- takes too long
- generates too many facts
- exceeds the iteration limit
fix #42
=> datalog: add world run limits

converters.go, converters_v0.go, converters_v0_test.go, converters_v1.go, converters_v1_test.go, example_test.go, pb/biscuit.pb.go, pb/biscuit.proto, types.go
This split the current protobuf schema into a v0 and v1 schema.
They are equivalent for now, but v0 is considered frozen, and v1 is free to
change with no BC guarantees.
New generated tokens will now hold v1 blocks, meaning they could not be
parsed by a v0 library. But older v0 tokens are still compatible with the v1
library.
=> bump block version to 1

parser/GRAMMAR.md, parser/grammar.go, parser/grammar_test.go, parser/parser_test.go
Date comparisons currently accept ">" and "<" operators, but the
comparison is done with ">=" and "<=". As per the spec, it must be the
latter, so the parser now enforce the usage of ">=" and "<=" for date
comparisons.
=> fix date comparison parsing

builder.go
The builder option `WihtRandom` should probably be `WithRandom`.
=> Fix typo in `builder.go`

.github/workflows/ci.yml, datalog/datalog.go, datalog/symbol.go, samples/samples_test.go
rewrite the datalog engine to run in a goroutine and send results over a channel. This allows us to construct facts lazily instead of pregenerating large lists
=> Refactor datalog engine

samples/samples_test.go
the linter was failing in a few other PRs due to use of the ioutil pkg
=> samples: use os.ReadFile vs ioutil.ReadFile in tests

datalog/expressions.go
I noticed a few `BinaryOp`s missing string representations for debug printing, so added them here.
=> datalog: BinaryOp.Print: add BinaryIntersection and BinaryUnion

authorizer.go, biscuit.go
I've run into some cases where the default world max duration wasn't quite enough, resulting in intermittent failures. This PR exposes options to the caller to override the default limits (and for completeness, the default symbol table).
e.g.
```go
b, err := biscuit.Unmarshal(token)
// ...
authorizer, err := b.Authorizer(
publicRoot,
biscuit.WithBaseWorld(
datalog.NewWorld(
datalog.WithMaxDuration(3 * time.Millisecond),
),
),
)
// ...
```
=> allow customizing base world & syms for authorizer

authorizer.go, biscuit.go, biscuit_test.go, builder.go, converters.go, converters_v2.go, converters_v2_test.go, example_test.go, experiments/pop_test.go, go.mod, parser/grammar.go, parser/grammar_test.go, parser/parser.go, parser/parser_test.go, samples/samples_test.go, types.go, types_test.go, website_test.go
As outlined in #104, it's currently impossible to import v2 of this package.
This PR fixes the issue with the "release version in go.mod URL" strategy.
I've tested this at https://github.com/guregu/biscuit-go and it looks like it works well.
=> Fix v2 release

example_test.go, parser/grammar.go, parser/grammar_test.go, parser/parser.go, parser/parser_test.go, samples/samples_test.go
Parsed datalog snippets can now contain placeholders (for instance: `check if right({resource}, {operation}`). This allows embedding dynamic values in datalog, without the risk of injections.
All the `FromString*` methods now have a `FromString*WithParams` counterpart that take an extra
`map[string]Term` value.
/!\ For now, it is the caller's responsibility to make sure the all the placeholders **in expressions** have a corresponding value defined (same as making sure sets don't contain variables).
Placeholders set in predicates don't have this issue. This is an underlying issue of the parser; it was not introduced by this change.
=> Parameters

biscuit.go, biscuit_test.go, builder.go, options.go
In order to accommodate biscuit issuers with multiple key pairs in use, whether concurrently or in an ongoing rotation cycle, biscuits can record and expose an identifier for the root private key used to sign its authority block. Allow issuers to associate such an identifier with the private key when creating a new biscuit.
Introduce the option function `WithRootKeyID` to supply such an identifier at composition time, and the `(*Biscuit).RootKeyID` method to query this identifier later.
Contributes to #150.
=> Allow associating an ID with a biscuit's root key

biscuit.go, biscuit_test.go, builder.go
To be able to set a context and retrieve it form a biscuit.
=> Add SetContext on Builder interface and GetContext on Biscuit struct.

biscuit.go, biscuit_test.go
In order to more easily accommodate rotating of root private keys when issuing biscuits, allow consumers to choose which root public key to use when verifying the biscuit based on the key ID embedded within it at composition time, if any. Consumers can then accept biscuits signed with several root keys, learning to accept signatures from a rolling set of both older and newer keys.
Introduce the `(*Biscuit).AuthorizerFor` method as an eventual replacement for the longstanding `(*Biscuit).Authorizer` method, along with with two new options for supplying either a single public key or a mapping from ID to public key (together with an optional default public key to use when the biscuit in question embeds no root key ID). Alternately, callers may supply a projection function that consumes an …
=> Allow selecting root public key by ID
